services:
- docker
# before_install:
# - echo -e "machine github.ibm.com\n  login $GITHUB_TOKEN" > ~/.netrc
# - git lfs pull
before_script:
- echo "Install IBM Cloud CLI"
- curl -sL https://ibm.biz/idt-installer | bash
- ibmcloud plugin update container-service
- ibmcloud plugin update container-registry
- echo "Install kubectl"
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
script: echo 'Building Docker image with tags'
after_success:
- export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`
- export git_repo=$(echo $TRAVIS_REPO_SLUG |  awk -F"/" '{print tolower($2)}')
- export icp_name="$git_repo"-icp
- docker build -t $git_repo -f Dockerfile .
- docker tag  $git_repo "$DOCKER_USERNAME"/$git_repo:$TRAVIS_BRANCH-$DEPLOY_TIMESTAMP-$TRAVIS_BUILD_NUMBER
#SG- docker tag  $git_repo "$DOCKER_USERNAME"/$git_repo:latest
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./scripts/* && ./scripts/deploy-r.sh
  on:
    branch: master
after_deploy:
- NODEPORT=$(kubectl get -o jsonpath="{.spec.ports[0].nodePort}" services "$git_repo")
- NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalIP")].address}')
- export url=http://"$NODES":"$NODEPORT"
- export short_url=$(curl -s http://tinyurl.com/api-create.php?url=${url})
- echo ${short_url}
